//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleX.Common.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleX.Common.Enums.EnumResource", typeof(EnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string AddressType_Default {
            get {
                return ResourceManager.GetString("AddressType.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string AddressType_Delivery {
            get {
                return ResourceManager.GetString("AddressType.Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string AddressType_Invoice {
            get {
                return ResourceManager.GetString("AddressType.Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        internal static string CountryCode_AD {
            get {
                return ResourceManager.GetString("CountryCode.AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Arab Emirates.
        /// </summary>
        internal static string CountryCode_AE {
            get {
                return ResourceManager.GetString("CountryCode.AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        internal static string CountryCode_AF {
            get {
                return ResourceManager.GetString("CountryCode.AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua and Barbuda.
        /// </summary>
        internal static string CountryCode_AG {
            get {
                return ResourceManager.GetString("CountryCode.AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anguilla.
        /// </summary>
        internal static string CountryCode_AI {
            get {
                return ResourceManager.GetString("CountryCode.AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        internal static string CountryCode_AL {
            get {
                return ResourceManager.GetString("CountryCode.AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        internal static string CountryCode_AM {
            get {
                return ResourceManager.GetString("CountryCode.AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angola.
        /// </summary>
        internal static string CountryCode_AO {
            get {
                return ResourceManager.GetString("CountryCode.AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antarctica.
        /// </summary>
        internal static string CountryCode_AQ {
            get {
                return ResourceManager.GetString("CountryCode.AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        internal static string CountryCode_AR {
            get {
                return ResourceManager.GetString("CountryCode.AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Samoa.
        /// </summary>
        internal static string CountryCode_AS {
            get {
                return ResourceManager.GetString("CountryCode.AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        internal static string CountryCode_AT {
            get {
                return ResourceManager.GetString("CountryCode.AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string CountryCode_AU {
            get {
                return ResourceManager.GetString("CountryCode.AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba.
        /// </summary>
        internal static string CountryCode_AW {
            get {
                return ResourceManager.GetString("CountryCode.AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åland Islands.
        /// </summary>
        internal static string CountryCode_AX {
            get {
                return ResourceManager.GetString("CountryCode.AX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        internal static string CountryCode_AZ {
            get {
                return ResourceManager.GetString("CountryCode.AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina.
        /// </summary>
        internal static string CountryCode_BA {
            get {
                return ResourceManager.GetString("CountryCode.BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbados.
        /// </summary>
        internal static string CountryCode_BB {
            get {
                return ResourceManager.GetString("CountryCode.BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        internal static string CountryCode_BD {
            get {
                return ResourceManager.GetString("CountryCode.BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        internal static string CountryCode_BE {
            get {
                return ResourceManager.GetString("CountryCode.BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso.
        /// </summary>
        internal static string CountryCode_BF {
            get {
                return ResourceManager.GetString("CountryCode.BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        internal static string CountryCode_BG {
            get {
                return ResourceManager.GetString("CountryCode.BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        internal static string CountryCode_BH {
            get {
                return ResourceManager.GetString("CountryCode.BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundi.
        /// </summary>
        internal static string CountryCode_BI {
            get {
                return ResourceManager.GetString("CountryCode.BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benin.
        /// </summary>
        internal static string CountryCode_BJ {
            get {
                return ResourceManager.GetString("CountryCode.BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Barthélemy.
        /// </summary>
        internal static string CountryCode_BL {
            get {
                return ResourceManager.GetString("CountryCode.BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bermuda.
        /// </summary>
        internal static string CountryCode_BM {
            get {
                return ResourceManager.GetString("CountryCode.BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei Darussalam.
        /// </summary>
        internal static string CountryCode_BN {
            get {
                return ResourceManager.GetString("CountryCode.BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia.
        /// </summary>
        internal static string CountryCode_BO {
            get {
                return ResourceManager.GetString("CountryCode.BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonaire, Saint Eustatius and Saba.
        /// </summary>
        internal static string CountryCode_BQ {
            get {
                return ResourceManager.GetString("CountryCode.BQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        internal static string CountryCode_BR {
            get {
                return ResourceManager.GetString("CountryCode.BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamas.
        /// </summary>
        internal static string CountryCode_BS {
            get {
                return ResourceManager.GetString("CountryCode.BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutan.
        /// </summary>
        internal static string CountryCode_BT {
            get {
                return ResourceManager.GetString("CountryCode.BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouvet Island.
        /// </summary>
        internal static string CountryCode_BV {
            get {
                return ResourceManager.GetString("CountryCode.BV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana.
        /// </summary>
        internal static string CountryCode_BW {
            get {
                return ResourceManager.GetString("CountryCode.BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        internal static string CountryCode_BY {
            get {
                return ResourceManager.GetString("CountryCode.BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize.
        /// </summary>
        internal static string CountryCode_BZ {
            get {
                return ResourceManager.GetString("CountryCode.BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string CountryCode_CA {
            get {
                return ResourceManager.GetString("CountryCode.CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocos (Keeling) Islands.
        /// </summary>
        internal static string CountryCode_CC {
            get {
                return ResourceManager.GetString("CountryCode.CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo.
        /// </summary>
        internal static string CountryCode_CD {
            get {
                return ResourceManager.GetString("CountryCode.CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Africa.
        /// </summary>
        internal static string CountryCode_CF {
            get {
                return ResourceManager.GetString("CountryCode.CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo.
        /// </summary>
        internal static string CountryCode_CG {
            get {
                return ResourceManager.GetString("CountryCode.CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        internal static string CountryCode_CH {
            get {
                return ResourceManager.GetString("CountryCode.CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cote d&apos;Ivoire.
        /// </summary>
        internal static string CountryCode_CI {
            get {
                return ResourceManager.GetString("CountryCode.CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook Islands.
        /// </summary>
        internal static string CountryCode_CK {
            get {
                return ResourceManager.GetString("CountryCode.CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        internal static string CountryCode_CL {
            get {
                return ResourceManager.GetString("CountryCode.CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameroon.
        /// </summary>
        internal static string CountryCode_CM {
            get {
                return ResourceManager.GetString("CountryCode.CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        internal static string CountryCode_CN {
            get {
                return ResourceManager.GetString("CountryCode.CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        internal static string CountryCode_CO {
            get {
                return ResourceManager.GetString("CountryCode.CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        internal static string CountryCode_CR {
            get {
                return ResourceManager.GetString("CountryCode.CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba.
        /// </summary>
        internal static string CountryCode_CU {
            get {
                return ResourceManager.GetString("CountryCode.CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cape Verde.
        /// </summary>
        internal static string CountryCode_CV {
            get {
                return ResourceManager.GetString("CountryCode.CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curaçao.
        /// </summary>
        internal static string CountryCode_CW {
            get {
                return ResourceManager.GetString("CountryCode.CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Island.
        /// </summary>
        internal static string CountryCode_CX {
            get {
                return ResourceManager.GetString("CountryCode.CX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus.
        /// </summary>
        internal static string CountryCode_CY {
            get {
                return ResourceManager.GetString("CountryCode.CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        internal static string CountryCode_CZ {
            get {
                return ResourceManager.GetString("CountryCode.CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string CountryCode_DE {
            get {
                return ResourceManager.GetString("CountryCode.DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djibouti.
        /// </summary>
        internal static string CountryCode_DJ {
            get {
                return ResourceManager.GetString("CountryCode.DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        internal static string CountryCode_DK {
            get {
                return ResourceManager.GetString("CountryCode.DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominica.
        /// </summary>
        internal static string CountryCode_DM {
            get {
                return ResourceManager.GetString("CountryCode.DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        internal static string CountryCode_DO {
            get {
                return ResourceManager.GetString("CountryCode.DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria.
        /// </summary>
        internal static string CountryCode_DZ {
            get {
                return ResourceManager.GetString("CountryCode.DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuador.
        /// </summary>
        internal static string CountryCode_EC {
            get {
                return ResourceManager.GetString("CountryCode.EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        internal static string CountryCode_EE {
            get {
                return ResourceManager.GetString("CountryCode.EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        internal static string CountryCode_EG {
            get {
                return ResourceManager.GetString("CountryCode.EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Sahara.
        /// </summary>
        internal static string CountryCode_EH {
            get {
                return ResourceManager.GetString("CountryCode.EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eritrea.
        /// </summary>
        internal static string CountryCode_ER {
            get {
                return ResourceManager.GetString("CountryCode.ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string CountryCode_ES {
            get {
                return ResourceManager.GetString("CountryCode.ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopia.
        /// </summary>
        internal static string CountryCode_ET {
            get {
                return ResourceManager.GetString("CountryCode.ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        internal static string CountryCode_FI {
            get {
                return ResourceManager.GetString("CountryCode.FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji.
        /// </summary>
        internal static string CountryCode_FJ {
            get {
                return ResourceManager.GetString("CountryCode.FJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falkland Islands (Malvinas).
        /// </summary>
        internal static string CountryCode_FK {
            get {
                return ResourceManager.GetString("CountryCode.FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micronesia.
        /// </summary>
        internal static string CountryCode_FM {
            get {
                return ResourceManager.GetString("CountryCode.FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        internal static string CountryCode_FO {
            get {
                return ResourceManager.GetString("CountryCode.FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string CountryCode_FR {
            get {
                return ResourceManager.GetString("CountryCode.FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabon.
        /// </summary>
        internal static string CountryCode_GA {
            get {
                return ResourceManager.GetString("CountryCode.GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string CountryCode_GB {
            get {
                return ResourceManager.GetString("CountryCode.GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenada.
        /// </summary>
        internal static string CountryCode_GD {
            get {
                return ResourceManager.GetString("CountryCode.GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string CountryCode_GE {
            get {
                return ResourceManager.GetString("CountryCode.GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Guiana.
        /// </summary>
        internal static string CountryCode_GF {
            get {
                return ResourceManager.GetString("CountryCode.GF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guernsey.
        /// </summary>
        internal static string CountryCode_GG {
            get {
                return ResourceManager.GetString("CountryCode.GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghana.
        /// </summary>
        internal static string CountryCode_GH {
            get {
                return ResourceManager.GetString("CountryCode.GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibraltar.
        /// </summary>
        internal static string CountryCode_GI {
            get {
                return ResourceManager.GetString("CountryCode.GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        internal static string CountryCode_GL {
            get {
                return ResourceManager.GetString("CountryCode.GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambia.
        /// </summary>
        internal static string CountryCode_GM {
            get {
                return ResourceManager.GetString("CountryCode.GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea.
        /// </summary>
        internal static string CountryCode_GN {
            get {
                return ResourceManager.GetString("CountryCode.GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guadeloupe.
        /// </summary>
        internal static string CountryCode_GP {
            get {
                return ResourceManager.GetString("CountryCode.GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equatorial Guinea.
        /// </summary>
        internal static string CountryCode_GQ {
            get {
                return ResourceManager.GetString("CountryCode.GQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        internal static string CountryCode_GR {
            get {
                return ResourceManager.GetString("CountryCode.GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Georgia and the South Sandwich Islands.
        /// </summary>
        internal static string CountryCode_GS {
            get {
                return ResourceManager.GetString("CountryCode.GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        internal static string CountryCode_GT {
            get {
                return ResourceManager.GetString("CountryCode.GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        internal static string CountryCode_GU {
            get {
                return ResourceManager.GetString("CountryCode.GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea-Bissau.
        /// </summary>
        internal static string CountryCode_GW {
            get {
                return ResourceManager.GetString("CountryCode.GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyana.
        /// </summary>
        internal static string CountryCode_GY {
            get {
                return ResourceManager.GetString("CountryCode.GY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        internal static string CountryCode_HK {
            get {
                return ResourceManager.GetString("CountryCode.HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heard Island and Mcdonald Islands.
        /// </summary>
        internal static string CountryCode_HM {
            get {
                return ResourceManager.GetString("CountryCode.HM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        internal static string CountryCode_HN {
            get {
                return ResourceManager.GetString("CountryCode.HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        internal static string CountryCode_HR {
            get {
                return ResourceManager.GetString("CountryCode.HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiti.
        /// </summary>
        internal static string CountryCode_HT {
            get {
                return ResourceManager.GetString("CountryCode.HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        internal static string CountryCode_HU {
            get {
                return ResourceManager.GetString("CountryCode.HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        internal static string CountryCode_ID {
            get {
                return ResourceManager.GetString("CountryCode.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        internal static string CountryCode_IE {
            get {
                return ResourceManager.GetString("CountryCode.IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        internal static string CountryCode_IL {
            get {
                return ResourceManager.GetString("CountryCode.IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isle of Man.
        /// </summary>
        internal static string CountryCode_IM {
            get {
                return ResourceManager.GetString("CountryCode.IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        internal static string CountryCode_IN {
            get {
                return ResourceManager.GetString("CountryCode.IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Indian Ocean Territory.
        /// </summary>
        internal static string CountryCode_IO {
            get {
                return ResourceManager.GetString("CountryCode.IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraq.
        /// </summary>
        internal static string CountryCode_IQ {
            get {
                return ResourceManager.GetString("CountryCode.IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran.
        /// </summary>
        internal static string CountryCode_IR {
            get {
                return ResourceManager.GetString("CountryCode.IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        internal static string CountryCode_IS {
            get {
                return ResourceManager.GetString("CountryCode.IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string CountryCode_IT {
            get {
                return ResourceManager.GetString("CountryCode.IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jersey.
        /// </summary>
        internal static string CountryCode_JE {
            get {
                return ResourceManager.GetString("CountryCode.JE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaica.
        /// </summary>
        internal static string CountryCode_JM {
            get {
                return ResourceManager.GetString("CountryCode.JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordan.
        /// </summary>
        internal static string CountryCode_JO {
            get {
                return ResourceManager.GetString("CountryCode.JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        internal static string CountryCode_JP {
            get {
                return ResourceManager.GetString("CountryCode.JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        internal static string CountryCode_KE {
            get {
                return ResourceManager.GetString("CountryCode.KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyzstan.
        /// </summary>
        internal static string CountryCode_KG {
            get {
                return ResourceManager.GetString("CountryCode.KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia.
        /// </summary>
        internal static string CountryCode_KH {
            get {
                return ResourceManager.GetString("CountryCode.KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribati.
        /// </summary>
        internal static string CountryCode_KI {
            get {
                return ResourceManager.GetString("CountryCode.KI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comoros.
        /// </summary>
        internal static string CountryCode_KM {
            get {
                return ResourceManager.GetString("CountryCode.KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Kitts and Nevis.
        /// </summary>
        internal static string CountryCode_KN {
            get {
                return ResourceManager.GetString("CountryCode.KN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Korea.
        /// </summary>
        internal static string CountryCode_KP {
            get {
                return ResourceManager.GetString("CountryCode.KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korea.
        /// </summary>
        internal static string CountryCode_KR {
            get {
                return ResourceManager.GetString("CountryCode.KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        internal static string CountryCode_KW {
            get {
                return ResourceManager.GetString("CountryCode.KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cayman Islands.
        /// </summary>
        internal static string CountryCode_KY {
            get {
                return ResourceManager.GetString("CountryCode.KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        internal static string CountryCode_KZ {
            get {
                return ResourceManager.GetString("CountryCode.KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        internal static string CountryCode_LA {
            get {
                return ResourceManager.GetString("CountryCode.LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        internal static string CountryCode_LB {
            get {
                return ResourceManager.GetString("CountryCode.LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Lucia.
        /// </summary>
        internal static string CountryCode_LC {
            get {
                return ResourceManager.GetString("CountryCode.LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        internal static string CountryCode_LI {
            get {
                return ResourceManager.GetString("CountryCode.LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        internal static string CountryCode_LK {
            get {
                return ResourceManager.GetString("CountryCode.LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberia.
        /// </summary>
        internal static string CountryCode_LR {
            get {
                return ResourceManager.GetString("CountryCode.LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesotho.
        /// </summary>
        internal static string CountryCode_LS {
            get {
                return ResourceManager.GetString("CountryCode.LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        internal static string CountryCode_LT {
            get {
                return ResourceManager.GetString("CountryCode.LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        internal static string CountryCode_LU {
            get {
                return ResourceManager.GetString("CountryCode.LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        internal static string CountryCode_LV {
            get {
                return ResourceManager.GetString("CountryCode.LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libya.
        /// </summary>
        internal static string CountryCode_LY {
            get {
                return ResourceManager.GetString("CountryCode.LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        internal static string CountryCode_MA {
            get {
                return ResourceManager.GetString("CountryCode.MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        internal static string CountryCode_MC {
            get {
                return ResourceManager.GetString("CountryCode.MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldova.
        /// </summary>
        internal static string CountryCode_MD {
            get {
                return ResourceManager.GetString("CountryCode.MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        internal static string CountryCode_ME {
            get {
                return ResourceManager.GetString("CountryCode.ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Martin (French Part).
        /// </summary>
        internal static string CountryCode_MF {
            get {
                return ResourceManager.GetString("CountryCode.MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        internal static string CountryCode_MG {
            get {
                return ResourceManager.GetString("CountryCode.MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshall Islands.
        /// </summary>
        internal static string CountryCode_MH {
            get {
                return ResourceManager.GetString("CountryCode.MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Macedonia.
        /// </summary>
        internal static string CountryCode_MK {
            get {
                return ResourceManager.GetString("CountryCode.MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali.
        /// </summary>
        internal static string CountryCode_ML {
            get {
                return ResourceManager.GetString("CountryCode.ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar.
        /// </summary>
        internal static string CountryCode_MM {
            get {
                return ResourceManager.GetString("CountryCode.MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        internal static string CountryCode_MN {
            get {
                return ResourceManager.GetString("CountryCode.MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macao.
        /// </summary>
        internal static string CountryCode_MO {
            get {
                return ResourceManager.GetString("CountryCode.MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Mariana Islands.
        /// </summary>
        internal static string CountryCode_MP {
            get {
                return ResourceManager.GetString("CountryCode.MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martinique.
        /// </summary>
        internal static string CountryCode_MQ {
            get {
                return ResourceManager.GetString("CountryCode.MQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritania.
        /// </summary>
        internal static string CountryCode_MR {
            get {
                return ResourceManager.GetString("CountryCode.MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montserrat.
        /// </summary>
        internal static string CountryCode_MS {
            get {
                return ResourceManager.GetString("CountryCode.MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        internal static string CountryCode_MT {
            get {
                return ResourceManager.GetString("CountryCode.MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritius.
        /// </summary>
        internal static string CountryCode_MU {
            get {
                return ResourceManager.GetString("CountryCode.MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives.
        /// </summary>
        internal static string CountryCode_MV {
            get {
                return ResourceManager.GetString("CountryCode.MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawi.
        /// </summary>
        internal static string CountryCode_MW {
            get {
                return ResourceManager.GetString("CountryCode.MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        internal static string CountryCode_MX {
            get {
                return ResourceManager.GetString("CountryCode.MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        internal static string CountryCode_MY {
            get {
                return ResourceManager.GetString("CountryCode.MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambique.
        /// </summary>
        internal static string CountryCode_MZ {
            get {
                return ResourceManager.GetString("CountryCode.MZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia.
        /// </summary>
        internal static string CountryCode_NA {
            get {
                return ResourceManager.GetString("CountryCode.NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Caledonia.
        /// </summary>
        internal static string CountryCode_NC {
            get {
                return ResourceManager.GetString("CountryCode.NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niger.
        /// </summary>
        internal static string CountryCode_NE {
            get {
                return ResourceManager.GetString("CountryCode.NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norfolk Island.
        /// </summary>
        internal static string CountryCode_NF {
            get {
                return ResourceManager.GetString("CountryCode.NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        internal static string CountryCode_NG {
            get {
                return ResourceManager.GetString("CountryCode.NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        internal static string CountryCode_NI {
            get {
                return ResourceManager.GetString("CountryCode.NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Netherlands.
        /// </summary>
        internal static string CountryCode_NL {
            get {
                return ResourceManager.GetString("CountryCode.NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string CountryCode_NO {
            get {
                return ResourceManager.GetString("CountryCode.NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        internal static string CountryCode_NP {
            get {
                return ResourceManager.GetString("CountryCode.NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauru.
        /// </summary>
        internal static string CountryCode_NR {
            get {
                return ResourceManager.GetString("CountryCode.NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niue.
        /// </summary>
        internal static string CountryCode_NU {
            get {
                return ResourceManager.GetString("CountryCode.NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        internal static string CountryCode_NZ {
            get {
                return ResourceManager.GetString("CountryCode.NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        internal static string CountryCode_OM {
            get {
                return ResourceManager.GetString("CountryCode.OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        internal static string CountryCode_PA {
            get {
                return ResourceManager.GetString("CountryCode.PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string CountryCode_PE {
            get {
                return ResourceManager.GetString("CountryCode.PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Polynesia.
        /// </summary>
        internal static string CountryCode_PF {
            get {
                return ResourceManager.GetString("CountryCode.PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papua New Guinea.
        /// </summary>
        internal static string CountryCode_PG {
            get {
                return ResourceManager.GetString("CountryCode.PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        internal static string CountryCode_PH {
            get {
                return ResourceManager.GetString("CountryCode.PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        internal static string CountryCode_PK {
            get {
                return ResourceManager.GetString("CountryCode.PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        internal static string CountryCode_PL {
            get {
                return ResourceManager.GetString("CountryCode.PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Pierre and Miquelon.
        /// </summary>
        internal static string CountryCode_PM {
            get {
                return ResourceManager.GetString("CountryCode.PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitcairn.
        /// </summary>
        internal static string CountryCode_PN {
            get {
                return ResourceManager.GetString("CountryCode.PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        internal static string CountryCode_PR {
            get {
                return ResourceManager.GetString("CountryCode.PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestinian Territory, Occupied.
        /// </summary>
        internal static string CountryCode_PS {
            get {
                return ResourceManager.GetString("CountryCode.PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        internal static string CountryCode_PT {
            get {
                return ResourceManager.GetString("CountryCode.PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palau.
        /// </summary>
        internal static string CountryCode_PW {
            get {
                return ResourceManager.GetString("CountryCode.PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        internal static string CountryCode_PY {
            get {
                return ResourceManager.GetString("CountryCode.PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        internal static string CountryCode_QA {
            get {
                return ResourceManager.GetString("CountryCode.QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réunion.
        /// </summary>
        internal static string CountryCode_RE {
            get {
                return ResourceManager.GetString("CountryCode.RE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        internal static string CountryCode_RO {
            get {
                return ResourceManager.GetString("CountryCode.RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        internal static string CountryCode_RS {
            get {
                return ResourceManager.GetString("CountryCode.RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string CountryCode_RU {
            get {
                return ResourceManager.GetString("CountryCode.RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda.
        /// </summary>
        internal static string CountryCode_RW {
            get {
                return ResourceManager.GetString("CountryCode.RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabia.
        /// </summary>
        internal static string CountryCode_SA {
            get {
                return ResourceManager.GetString("CountryCode.SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solomon Islands.
        /// </summary>
        internal static string CountryCode_SB {
            get {
                return ResourceManager.GetString("CountryCode.SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychelles.
        /// </summary>
        internal static string CountryCode_SC {
            get {
                return ResourceManager.GetString("CountryCode.SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudan.
        /// </summary>
        internal static string CountryCode_SD {
            get {
                return ResourceManager.GetString("CountryCode.SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string CountryCode_SE {
            get {
                return ResourceManager.GetString("CountryCode.SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        internal static string CountryCode_SG {
            get {
                return ResourceManager.GetString("CountryCode.SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Helena, Ascension and Tristan da Cunha.
        /// </summary>
        internal static string CountryCode_SH {
            get {
                return ResourceManager.GetString("CountryCode.SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        internal static string CountryCode_SI {
            get {
                return ResourceManager.GetString("CountryCode.SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svalbard and Jan Mayen.
        /// </summary>
        internal static string CountryCode_SJ {
            get {
                return ResourceManager.GetString("CountryCode.SJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        internal static string CountryCode_SK {
            get {
                return ResourceManager.GetString("CountryCode.SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone.
        /// </summary>
        internal static string CountryCode_SL {
            get {
                return ResourceManager.GetString("CountryCode.SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        internal static string CountryCode_SM {
            get {
                return ResourceManager.GetString("CountryCode.SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegal.
        /// </summary>
        internal static string CountryCode_SN {
            get {
                return ResourceManager.GetString("CountryCode.SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somalia.
        /// </summary>
        internal static string CountryCode_SO {
            get {
                return ResourceManager.GetString("CountryCode.SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suriname.
        /// </summary>
        internal static string CountryCode_SR {
            get {
                return ResourceManager.GetString("CountryCode.SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Sudan.
        /// </summary>
        internal static string CountryCode_SS {
            get {
                return ResourceManager.GetString("CountryCode.SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tome and Principe.
        /// </summary>
        internal static string CountryCode_ST {
            get {
                return ResourceManager.GetString("CountryCode.ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        internal static string CountryCode_SV {
            get {
                return ResourceManager.GetString("CountryCode.SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sint Maarten (Dutch Part).
        /// </summary>
        internal static string CountryCode_SX {
            get {
                return ResourceManager.GetString("CountryCode.SX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syria.
        /// </summary>
        internal static string CountryCode_SY {
            get {
                return ResourceManager.GetString("CountryCode.SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaziland.
        /// </summary>
        internal static string CountryCode_SZ {
            get {
                return ResourceManager.GetString("CountryCode.SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turks and Caicos Islands.
        /// </summary>
        internal static string CountryCode_TC {
            get {
                return ResourceManager.GetString("CountryCode.TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chad.
        /// </summary>
        internal static string CountryCode_TD {
            get {
                return ResourceManager.GetString("CountryCode.TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Southern Territories.
        /// </summary>
        internal static string CountryCode_TF {
            get {
                return ResourceManager.GetString("CountryCode.TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Togo.
        /// </summary>
        internal static string CountryCode_TG {
            get {
                return ResourceManager.GetString("CountryCode.TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        internal static string CountryCode_TH {
            get {
                return ResourceManager.GetString("CountryCode.TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        internal static string CountryCode_TJ {
            get {
                return ResourceManager.GetString("CountryCode.TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokelau.
        /// </summary>
        internal static string CountryCode_TK {
            get {
                return ResourceManager.GetString("CountryCode.TK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Timor.
        /// </summary>
        internal static string CountryCode_TL {
            get {
                return ResourceManager.GetString("CountryCode.TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        internal static string CountryCode_TM {
            get {
                return ResourceManager.GetString("CountryCode.TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisia.
        /// </summary>
        internal static string CountryCode_TN {
            get {
                return ResourceManager.GetString("CountryCode.TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonga.
        /// </summary>
        internal static string CountryCode_TO {
            get {
                return ResourceManager.GetString("CountryCode.TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        internal static string CountryCode_TR {
            get {
                return ResourceManager.GetString("CountryCode.TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidad and Tobago.
        /// </summary>
        internal static string CountryCode_TT {
            get {
                return ResourceManager.GetString("CountryCode.TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuvalu.
        /// </summary>
        internal static string CountryCode_TV {
            get {
                return ResourceManager.GetString("CountryCode.TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan, Province Of China.
        /// </summary>
        internal static string CountryCode_TW {
            get {
                return ResourceManager.GetString("CountryCode.TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzania.
        /// </summary>
        internal static string CountryCode_TZ {
            get {
                return ResourceManager.GetString("CountryCode.TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string CountryCode_UA {
            get {
                return ResourceManager.GetString("CountryCode.UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uganda.
        /// </summary>
        internal static string CountryCode_UG {
            get {
                return ResourceManager.GetString("CountryCode.UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States Minor Outlying Islands.
        /// </summary>
        internal static string CountryCode_UM {
            get {
                return ResourceManager.GetString("CountryCode.UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        internal static string CountryCode_US {
            get {
                return ResourceManager.GetString("CountryCode.US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        internal static string CountryCode_UY {
            get {
                return ResourceManager.GetString("CountryCode.UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        internal static string CountryCode_UZ {
            get {
                return ResourceManager.GetString("CountryCode.UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy See.
        /// </summary>
        internal static string CountryCode_VA {
            get {
                return ResourceManager.GetString("CountryCode.VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Vincent and the Grenadines.
        /// </summary>
        internal static string CountryCode_VC {
            get {
                return ResourceManager.GetString("CountryCode.VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        internal static string CountryCode_VE {
            get {
                return ResourceManager.GetString("CountryCode.VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Virgin Islands.
        /// </summary>
        internal static string CountryCode_VG {
            get {
                return ResourceManager.GetString("CountryCode.VG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgin Islands of the United States.
        /// </summary>
        internal static string CountryCode_VI {
            get {
                return ResourceManager.GetString("CountryCode.VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        internal static string CountryCode_VN {
            get {
                return ResourceManager.GetString("CountryCode.VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanuatu.
        /// </summary>
        internal static string CountryCode_VU {
            get {
                return ResourceManager.GetString("CountryCode.VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallis and Futuna.
        /// </summary>
        internal static string CountryCode_WF {
            get {
                return ResourceManager.GetString("CountryCode.WF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa.
        /// </summary>
        internal static string CountryCode_WS {
            get {
                return ResourceManager.GetString("CountryCode.WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CountryCode_XX {
            get {
                return ResourceManager.GetString("CountryCode.XX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemen.
        /// </summary>
        internal static string CountryCode_YE {
            get {
                return ResourceManager.GetString("CountryCode.YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayotte.
        /// </summary>
        internal static string CountryCode_YT {
            get {
                return ResourceManager.GetString("CountryCode.YT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        internal static string CountryCode_ZA {
            get {
                return ResourceManager.GetString("CountryCode.ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambia.
        /// </summary>
        internal static string CountryCode_ZM {
            get {
                return ResourceManager.GetString("CountryCode.ZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe.
        /// </summary>
        internal static string CountryCode_ZW {
            get {
                return ResourceManager.GetString("CountryCode.ZW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string CurrencyCode_EUR {
            get {
                return ResourceManager.GetString("CurrencyCode.EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound.
        /// </summary>
        internal static string CurrencyCode_GBP {
            get {
                return ResourceManager.GetString("CurrencyCode.GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Dollar.
        /// </summary>
        internal static string CurrencyCode_USD {
            get {
                return ResourceManager.GetString("CurrencyCode.USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string LanguageCode_DE {
            get {
                return ResourceManager.GetString("LanguageCode.DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageCode_EN {
            get {
                return ResourceManager.GetString("LanguageCode.EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string LanguageCode_FR {
            get {
                return ResourceManager.GetString("LanguageCode.FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string LanguageCode_NL {
            get {
                return ResourceManager.GetString("LanguageCode.NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string TaxCode_Default {
            get {
                return ResourceManager.GetString("TaxCode.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEG.
        /// </summary>
        internal static string TaxCode_EEG {
            get {
                return ResourceManager.GetString("TaxCode.EEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string TaxCode_None {
            get {
                return ResourceManager.GetString("TaxCode.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None EEG.
        /// </summary>
        internal static string TaxCode_NonEEG {
            get {
                return ResourceManager.GetString("TaxCode.NonEEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string TaxCode_Private {
            get {
                return ResourceManager.GetString("TaxCode.Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string TermOfPayment_Cash {
            get {
                return ResourceManager.GetString("TermOfPayment.Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 days.
        /// </summary>
        internal static string TermOfPayment_Day_14 {
            get {
                return ResourceManager.GetString("TermOfPayment.Day_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 days.
        /// </summary>
        internal static string TermOfPayment_Day_30 {
            get {
                return ResourceManager.GetString("TermOfPayment.Day_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 days.
        /// </summary>
        internal static string TermOfPayment_Day_60 {
            get {
                return ResourceManager.GetString("TermOfPayment.Day_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        internal static string TermOfPayment_Day_7 {
            get {
                return ResourceManager.GetString("TermOfPayment.Day_7", resourceCulture);
            }
        }
    }
}
